### ISSUE TITLE
make check fails

### ISSUE THREAD

**Issue by hailfinger** [OpenChannelSSD/qemu-nvme#10]
```
$ make check
[...]
  CC    tests/vhost-user-test.o
  LINK  tests/vhost-user-test
  CC    tests/qom-test.o
  LINK  tests/qom-test
GTESTER check-qtest-x86_64
blkdebug: Suspended request 'A'
blkdebug: Resuming request 'A'
main-loop: WARNING: I/O thread spun for 1000 iterations
main-loop: WARNING: I/O thread spun for 1000 iterations
Broken pipe
[vmxnet3][WR][vmxnet3_peer_has_vnet_hdr]: Peer has no virtio extension. Task offloads will be emulated.
/home/kubuntu/qemu-experimental/tests/Makefile:398: recipe for target 'check-qtest-x86_64' failed
make: *** [check-qtest-x86_64] Error 1
```

The `broken pipe` is actually what triggers the test failure. The vmxnet3 message is harmless.

bisection result:
First bad commit ff646a5841f743fdd9cfef138ac6be1f0ba4fbfb
Author: Keith Busch <keith.busch@intel.com>  2014-10-23 20:02:44
Committer: Keith Busch <keith.busch@intel.com>  2014-10-23 20:02:44
Parent: 4bee77be4ba07de204389ef054358347f8d69d74 (NVMe: Updates for google extension)
Parent: e40830afa1cff3ffdc37bdfdd40d80860074636c (Merge remote-tracking branch 'remotes/mdroth/tags/qga-pull-2014-10-22-tag' into staging)
    Merge remote-tracking branch 'upstream/master'
    
    Conflicts:
        hw/block/nvme.c
        hw/block/nvme.h
    
    As part of this, I am removing all meta-data support. It's not well
    supported in any immediatly available operating system, so the code is
    not well tested.
    
    Signed-off-by: Keith Busch <keith.busch@intel.com>

**Comment by javigon** [comment]
This comes from Keith's qemu-nvme. 

If you reproduce the error only using the nvme driver without LightNVM, you can open an issue on his qemu tree. Otherwise, this is mostly out of our realm (at least for now).

**Comment by hailfinger** [comment]
This is the output from the "make check" command run in the qemu tree directly, i.e. the official builtin qemu self-test. To remove any LightNVM stuff I'd have to edit hw/block/nvme.c.

It seems Keith doesn't host qemu-nvme on his github page. Do you happen to know where I can find his qemu-nvme?

**Comment by javigon** [comment]
I think the most updated one is here.

http://git.infradead.org/users/kbusch/qemu-nvme.git
