### ISSUE TITLE
[Feature] Please port OpenChannelSSD support to newer qemu

### ISSUE THREAD

**Issue by hailfinger** [OpenChannelSSD/qemu-nvme#12]
Compiling the current qemu-nvme tree on Ubuntu 16.04 yields two issues which break compilation: issue #11 (needs patching) and some deprecation warnings which need ./configure --disable-werror.

A newer qemu might possibly not have those issues. However, block device internals in qemu changed a lot since qemu-nvme was forked from mainline qemu, so porting might not be entirely straightforward.

**Comment by javigon** [comment]
Hi,

This will be nice. We do accept pull requests if you are up for the challenge :)

**Comment by javigon** [comment]
Hi hailfinger,

Is this still an issue?

Thanks,
Javier
