### ISSUE TITLE
Failure of installation of the latest qemu-nvme

### ISSUE THREAD

**Issue by nusbaoning** [OpenChannelSSD/qemu-nvme#13]
Hi! Thank you for looking at my question.
I tried to install the latest version of qemu-nvme with commit "6e5dab678c305f22a5f845156b570967910b3484" on my Ubuntu 16.04 with kernel 4.8.0-36-generic.
After make install, nothing special but there is no qemu installed. qemu-img, qemu-system-x86_64 don't work.
The result of make install:
install -d -m 0755 "/home/baoning/qemu-nvme/share/qemu"
install -d -m 0755 "/home/baoning/qemu-nvme/etc/qemu"
install -c -m 0644 /home/baoning/Downloads/qemu-nvme-6e5dab678c305f22a5f845156b570967910b3484/sysconfigs/target/target-x86_64.conf "/home/baoning/qemu-nvme/etc/qemu"
install -d -m 0755 "/home/baoning/qemu-nvme/var"/run
install -d -m 0755 "/home/baoning/qemu-nvme/bin"
install -c -m 0755 qemu-ga qemu-nbd qemu-img qemu-io  "/home/baoning/qemu-nvme/bin"
strip "/home/baoning/qemu-nvme/bin/qemu-ga" "/home/baoning/qemu-nvme/bin/qemu-nbd" "/home/baoning/qemu-nvme/bin/qemu-img" "/home/baoning/qemu-nvme/bin/qemu-io"
install -d -m 0755 "/home/baoning/qemu-nvme/libexec"
install -c -m 0755 qemu-bridge-helper "/home/baoning/qemu-nvme/libexec"
strip "/home/baoning/qemu-nvme/libexec/qemu-bridge-helper"
set -e; for x in bios.bin bios-256k.bin sgabios.bin vgabios.bin vgabios-cirrus.bin vgabios-stdvga.bin vgabios-vmware.bin vgabios-qxl.bin acpi-dsdt.aml q35-acpi-dsdt.aml ppc_rom.bin openbios-sparc32 openbios-sparc64 openbios-ppc QEMU,tcx.bin QEMU,cgthree.bin pxe-e1000.rom pxe-eepro100.rom pxe-ne2k_pci.rom pxe-pcnet.rom pxe-rtl8139.rom pxe-virtio.rom efi-e1000.rom efi-eepro100.rom efi-ne2k_pci.rom efi-pcnet.rom efi-rtl8139.rom efi-virtio.rom qemu-icon.bmp qemu_logo_no_text.svg bamboo.dtb petalogix-s3adsp1800.dtb petalogix-ml605.dtb multiboot.bin linuxboot.bin kvmvapic.bin s390-zipl.rom s390-ccw.img spapr-rtas.bin slof.bin palcode-clipper u-boot.e500; do \
	install -c -m 0644 /home/baoning/Downloads/qemu-nvme-6e5dab678c305f22a5f845156b570967910b3484/pc-bios/$x "/home/baoning/qemu-nvme/share/qemu"; \
done
install -d -m 0755 "/home/baoning/qemu-nvme/share/qemu/keymaps"
set -e; for x in da     en-gb  et  fr     fr-ch  is  lt  modifiers  no  pt-br  sv ar      de     en-us  fi  fr-be  hr     it  lv  nl         pl  ru     th common  de-ch  es     fo  fr-ca  hu     ja  mk  nl-be      pt  sl     tr bepo    cz; do \
	install -c -m 0644 /home/baoning/Downloads/qemu-nvme-6e5dab678c305f22a5f845156b570967910b3484/pc-bios/keymaps/$x "/home/baoning/qemu-nvme/share/qemu/keymaps"; \
done
install -c -m 0644 /home/baoning/Downloads/qemu-nvme-6e5dab678c305f22a5f845156b570967910b3484/trace-events "/home/baoning/qemu-nvme/share/qemu/trace-events"
for d in x86_64-softmmu; do \
make --no-print-directory BUILD_DIR=/home/baoning/Downloads/qemu-nvme-6e5dab678c305f22a5f845156b570967910b3484 TARGET_DIR=$d/ -C $d install || exit 1 ; \
        done
install -d -m 0755 "/home/baoning/qemu-nvme/bin"
install -c -m 0755 qemu-system-x86_64  "/home/baoning/qemu-nvme/bin"
strip "/home/baoning/qemu-nvme/bin/qemu-system-x86_64"
The configuration I use was 
./configure --python=/usr/bin/python2 --enable-kvm --target-list=x8
6_64-softmmu --enable-linux-aio --prefix=$HOME/qemu-nvme
The result of configuration is 
Disabling libtool due to broken toolchain support
Install prefix    /home/baoning/qemu-nvme
BIOS directory    /home/baoning/qemu-nvme/share/qemu
binary directory  /home/baoning/qemu-nvme/bin
library directory /home/baoning/qemu-nvme/lib
module directory  /home/baoning/qemu-nvme/lib/qemu
libexec directory /home/baoning/qemu-nvme/libexec
include directory /home/baoning/qemu-nvme/include
config directory  /home/baoning/qemu-nvme/etc
local state directory   /home/baoning/qemu-nvme/var
Manual directory  /home/baoning/qemu-nvme/share/man
ELF interp prefix /usr/gnemul/qemu-%M
Source path       /home/baoning/Downloads/qemu-nvme-6e5dab678c305f22a5f845156b570967910b3484
C compiler        cc
Host C compiler   cc
C++ compiler      c++
Objective-C compiler cc
ARFLAGS           rv
CFLAGS            -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g
QEMU_CFLAGS       -I/usr/include/pixman-1  -fPIE -DPIE -m64 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wall -Wundef -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing -fno-common  -Wendif-labels -Wmissing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-declaration -Wold-style-definition -Wtype-limits -fstack-protector-strong
LDFLAGS           -Wl,--warn-common -Wl,-z,relro -Wl,-z,now -pie -m64 -g
make              make
install           install
python            /usr/bin/python2 -B
smbd              /usr/sbin/smbd
module support    no
host CPU          x86_64
host big endian   no
target list       x86_64-softmmu
tcg debug enabled no
gprof enabled     no
sparse enabled    no
strip binaries    yes
profiler          no
static build      no
pixman            system
SDL support       no
GTK support       no
VTE support       no
curses support    no
curl support      no
mingw32 support   no
Audio drivers     oss
Block whitelist (rw)
Block whitelist (ro)
VirtFS support    no
VNC support       yes
VNC TLS support   no
VNC SASL support  no
VNC JPEG support  no
VNC PNG support   no
VNC WS support    no
xen support       no
brlapi support    no
bluez  support    no
Documentation     no
GUEST_BASE        yes
PIE               yes
vde support       no
netmap support    no
Linux AIO support yes
ATTR/XATTR support yes
Install blobs     yes
KVM support       yes
RDMA support      no
TCG interpreter   no
fdt support       no
preadv support    yes
fdatasync         yes
madvise           yes
posix_madvise     yes
sigev_thread_id   yes
uuid support      no
libcap-ng support no
vhost-net support yes
vhost-scsi support yes
Trace backends    nop
spice support     no
rbd support       no
xfsctl support    no
nss used          no
libusb            no
usb net redir     no
GLX support       no
libiscsi support  no
libnfs support    no
build guest agent yes
QGA VSS support   no
seccomp support   no
coroutine backend ucontext
coroutine pool    yes
GlusterFS support no
Archipelago support no
gcov              gcov
gcov enabled      no
TPM support       yes
libssh2 support   no
TPM passthrough   yes
QOM debugging     yes
vhdx              no
Quorum            no
lzo support       no
snappy support    no
NUMA host support no

**Comment by nusbaoning** [comment]
I found when I renamed the directory name as nvme-qemu, everything is fine.

**Comment by javigon** [comment]
Good to hear!
