### ISSUE TITLE
qemu-nvme in Docker

### ISSUE THREAD

**Issue by ljishen** [OpenChannelSSD/qemu-nvme#15]
Hi, I set up a repository that packages this qemu-nvme environment in Docker container. People who want to have a quick try of the LightNVM or run SPDK applications on top of this emulation env, I think this tool is a good starting point.

https://github.com/ljishen/nvme-env/tree/master/docker/qemu-nvme

Any comments and suggestions will be greatly appreciated.

**Comment by MatiasBjorling** [comment]
Awesome!!

This is very helpful. I will give it a try ASAP.
