### ISSUE TITLE
Question when reading erase function of lnvm

### ISSUE THREAD

**Issue by nusbaoning** [OpenChannelSSD/qemu-nvme#16]
Hi. I want to write a function to record the erase times of each block for a .
I focused on /hw/block/nvme.c with commit 6e5dab67.
The function I located is lnvm_erase_async which first calls lnvm_meta_blk_set_erased then erase_io_complete_cb. Is this function a critical path for erasing operation?
Moreover, I am quite confused with the short names of different data granularities especially without comments, could you tell me which variables are used to represent the block ids?
Thank you so much

**Comment by javigon** [comment]
Erases are on the path the host decides. On pblk, erases are on the fast path, and the functions are the ones you mention.

We do not have blocks represented as such on qemu; we calculate the block position on each ppa. This is the way we can for example, make checks on erased blocks (lnvm_meta_state_set_written). If you want to hold more metadata, it might make sense to represent blocks as we do on the host stack.
