### ISSUE TITLE
What is your detailed configurations of host machine and virtual machine?

### ISSUE THREAD

**Issue by nusbaoning** [OpenChannelSSD/qemu-nvme#18]
Hi. Since I couldn't get a normal emulated nvme device, I want to fully copy your machine configurations. I believe that there must be some reasons that the device works normal on your device but not on mine. If it is possible, I'd like to download the back file of your virtual machine.
If not, could you provide me the following information:
1. The OS of your host machine and its release, f. ex., Ubuntu 16.10.
2. The kernel version of your host machine.
3. The version of the headers files needed by qemu-nvme, such as x86_64-softmmu, libaio.
4. What is the version of your qemu-nvme? What is the configuration of the software?
5. What is the version of the kernel in the virtual machine？ Could you provide the config file of the kernel?
6. What are the versions of header files needed by the kernel?
I know my question costs much time, especially when some of them seem irrelevant. But I failed too many times and wanted to be careful. Thank you so much for your support. 
If you are not available now, could you leave a message so that I can roughly know when I can get the answer.
If you dislike my question, pls tell me where is inappropriate.
Thank you again for all your help!

**Comment by javigon** [comment]
Hi nusbaoning,

I'm using the latest qemu and pblk.next. This is what we would always recommend.

On top of that here is my qemu configuration for lightnvm:

-device nvme,drive=mynvme,serial=deadbeef,namespaces=1,lver=1,lmetasize=16,ll2pmode=0,nlbaf=5,lba_index=3,mdts=10,lnum_lun=4,lnum_pln=2,lsec_size=4096,lsecs_per_pg=4,lpgs_per_blk=512,lbbtable=bbtable.qemu,lmetadata=meta.qemu,ldebug=1 \

**Comment by nusbaoning** [comment]
For pblk.next, which branch in https://github.com/OpenChannelSSD/linux do you mean? Or you are using other github projects?
How about your host machine? Which OS and kernel?
Thank you.

**Comment by javigon** [comment]
Can you pull the latest changes? (git pull --rebase $OCSSD_PROJECT pblk.next)

The host machine should no influence. But I'm using a Ubuntu 16.04 with 4.7 at this moment.

**Comment by nusbaoning** [comment]
Ok. You don't think the header files needed during the compilation and installation of qemu and linux kernel matter?

**Comment by javigon** [comment]
They do matter, but unless you are using an ancient distro and/or kernel the  you should be fine - the qemu version in which OCSSD simulation is based is pretty old.

**Comment by nusbaoning** [comment]
Hi. Both my host machine and my virtual machine is Ubuntu 16.04.
When I tried to compile and install the latest commit of pblk.next, I couldn't boot into the kernel.
It's either a black screen or showing that VFS can't be booted. Have you ever met such situation? Any clue? I did not make any change during make menuconfig. But I tested that all the necessary configurations for nvme is y. Anyway, this should not infect the boot stage since I haven't added the nvme drive to the qemu machine.
![image](https://user-images.githubusercontent.com/14070574/28963857-394c5c06-793d-11e7-9109-712f95725aae.png)
Thank you.

**Comment by javigon** [comment]
Hi,

A VFS problem is typically caused because you do not have a boot disk assigned in the the virtual machine.

**Comment by nusbaoning** [comment]
But I installed the new kernel inside the VM so no need to give any boot disk in the qemu command.

**Comment by nusbaoning** [comment]
Moreover, if I select the original 4.8 kernel, it can successfully boot.

**Comment by javigon** [comment]
I don't know why you have this error in this particular case, but it has nothing to do with LightNVM. My experience is that is occurs when you either (i) do not have a boot disk, (ii) cannot find the disk you are pointing to in the qemu config or (iii) if you have not compiled in a file system (but this is not very probable).

**Comment by nusbaoning** [comment]
Hi. One more thing to check.
The initial command is:
sudo nvme lnvm init -d nvme0n1
sudo nvme lnvm create -d nvme0n1 --lun-begin=0 --lun-end=3 -n mydevice -t pblk -f
right?
I found that when I ran fio to write the device for several times without verifying, it can exit normally. However, if I add verify function and run for several times, it will report bad header and _erase_meta: failed -- already erased will print in the host terminal.
So in you machine, fio write with verify also works normally?

**Comment by javigon** [comment]
Hi nusbaoning,

The "_erase_meta: failed -- already erased" is a known issue in the qemu block metadata. Avoid it for now; it does not mean anything in practice for the host.

**Comment by nusbaoning** [comment]
Do you mean "ignore it" by avoiding it?

**Comment by javigon** [comment]
It is a bug on the state assert in the qemu code. it is harmless. You are welcome to take a look at it and send a PR :)
