### ISSUE TITLE
g_mem_set_vtable’ is deprecated

### ISSUE THREAD

**Issue by andyandroid** [OpenChannelSSD/qemu-nvme#2]
I try to make the qemu-nvme on my Ubuntu, but encounter the following error, Could anybody help to fix it.

`andy@andy-MS-7758:~/qemu-nvme$ make 
  CC    vl.o
vl.c: In function ‘main’:
vl.c:2785:5: error: ‘g_mem_set_vtable’ is deprecated [-Werror=deprecated-declarations]
     g_mem_set_vtable(&mem_trace);
     ^
In file included from /usr/include/glib-2.0/glib/glist.h:32:0,
                 from /usr/include/glib-2.0/glib/ghash.h:33,
                 from /usr/include/glib-2.0/glib.h:50,
                 from vl.c:59:
/usr/include/glib-2.0/glib/gmem.h:357:7: note: declared here
 void  g_mem_set_vtable (GMemVTable *vtable);
       ^
cc1: all warnings being treated as errors
/home/andy/qemu-nvme/rules.mak:57: recipe for target 'vl.o' failed
make: *** [vl.o] Error 1
`

**Comment by MatiasBjorling** [comment]
Hi Andy,

What linux distribution and version are you running?

**Comment by MatiasBjorling** [comment]
Andy,

Please see if the latest master solve it.

Thanks,
Matias

**Comment by andyandroid** [comment]
Matias

Thanks, it is fixed.

At 2016-04-27 22:33:05, "Matias Bjørling" <notifications@github.com> wrote:


Andy,

Please see if the latest master solve it.

Thanks,
Matias
