### ISSUE TITLE
lnvm init error: <_set_written: Invalid block state(00)> on qemu

### ISSUE THREAD

**Issue by wangmir** [OpenChannelSSD/qemu-nvme#21]
Hi,

I'm currently working on qemu to run pblk at pblk.20 and pblk.for-4.13-fixes, and there are some problems.

First of all, I tried to run pblk.20 code at the qemu-nvme, but when I run lnvm init -d nvme0n1 -m gennvm,
qemu shows an error like this.

```
_set_written: Invalid block state(00)
lnvm_rw: set written status failed
ppa: ch(0), lun(0), blk(0), pg(0), pl(0), sec(0)

```

So, I just thought that pblk.20 is not supported by qemu-nvme.
But, are there any solution for this?

Secondly, thus, I tried to run pblk.for-4.13-fixes on qemu too.
In this case, I successfully init the device with lnvm init.

But, after that, I got same error I asked before at linux repository of OpenChannelSSD.
(https://github.com/OpenChannelSSD/linux/issues/37)

Do you have any solution for this?

or, can I get linux version and qemu option for successful running at current state?

Thanks,
Hyukjoong

**Comment by javigon** [comment]
Can you use the nvme-cli tool to initialize the pblk instance? 
   sudo nvme lnvm create -d nvme0n1 -t pblk -n pblk0 -b 0 -e 3 -f

When initializing a target, you need to specify more than you do in the command you show above. See
  http://lightnvm.io/pblk-tools/usage.html#bring-up-teardown

Also, pblk.20 is not maintained anymore. It was one of the versions that led to the pblk being merged upstream. Support starts at 4.12.

Regarding new versions, we will be moving with kernel windows. The latest merged is 4.14. You can get that either from the mainline kernel (when it is released) or from our repository. The current window we are working on is 4.15 (the branch is for-4.15/pblk), but it is a moving target until it gets merged.

Thanks
Javier

**Comment by wangmir** [comment]
Ok, I'll try the nvme-cli tool rather than lnvm.

Anyway, is it different from lnvm?, I tried this tool (https://github.com/OpenChannelSSD/lnvm), rather than nvme-cli, and it's instruction was, first: init, second: create.

And, additionally, I successfully ran pblk with branch pblk.cnex (with former lnvm tool), but I don't know what exactly is it.

**Comment by MatiasBjorling** [comment]
It has support for initializing pblk with factory-defaults. 

You can skip the init step on 4.8+ kernels. 

The pblk.cnex is a branch with latest pblk patches plus a couple of identification patches that are needed for CNEX controllers to be identified.

**Comment by wangmir** [comment]
I tried pblk.for-4.14 with nvme-cli tools, and it works well.

Thanks,
Hyukjoong

**Comment by javigon** [comment]
Cool! Can you then close the issues related to this?

Javier

**Comment by wangmir** [comment]
Ok, I'll close issue in here.
And in the case of https://github.com/OpenChannelSSD/linux/issues/37, I'll try on my emulator rather than qemu at the pblk.for-4.14, so I'll check the identify interface at that too, and then I'll close it too.

Thanks for help.

**Comment by javigon** [comment]
Cool.

You welcome!
