### ISSUE TITLE
Command Arbitration not supported

### ISSUE THREAD

**Issue by shashankgugnani** [OpenChannelSSD/qemu-nvme#22]
Each SQ uses its own QEMU timer, meaning that each SQ is processed independently, most likely in a separate thread. So, command arbitration techniques like weighted round robin don't work as expected.
Is there a reason for this implementation choice or is this a bug?

**Comment by javigon** [comment]
We used Keith Busch's qemu-nvme repository to build support for LightNVM; sq/cq pair management was inherited from it. 

This said, we use qemu for host sanity checks, so at least for now implementing support for different device-side arbitration algorithms is not a priority.

We do accept pull requests though; if you want to implement this.
