### ISSUE TITLE
Does qemu-nvme support multiple channel?

### ISSUE THREAD

**Issue by Raoxiaoman** [OpenChannelSSD/qemu-nvme#23]
Hi qemu-nvme developer

this my start.sh for qemu
```

sudo qemu-system-x86_64 -m 4096 -smp 4  -enable-kvm -hda openchannelssd.raw  \
    -drive file=blknvme,if=none,id=blknvme \
    -device nvme,drive=blknvme,serial=deadbeef,namespaces=1,lver=1,nlbaf=5,lba_index=3,mdts=10,lnum_ch=16,lnum_lun=1,lnum_pln=2 \
    -net nic,macaddr=54:52:d5:ab:83:10 -net tap,script=/etc/qemu-ifup   
    #-redir tcp:2223::22
    #-append "root=/dev/sda1" 
    #-kernel "/home/raohui/open_channel_ssd/linux/arch/x86_64/boot/bzImage" \

```
but the infortions is that:nvme: Only 1 channel is supported at the moment

Does qemu-nvme support multiple channel?

Thanks~
RaoXiaoMan

**Comment by javigon** [comment]
Hi RaoXiaoMan,

We do not simulate >1 channels since we have not implemented a mechanism to simulate parallelism in qemu. To experiment with isolation and striping you can just add more LUNs. 

Implementing multi-channel support without parallelism is fairly trivial though.

Thanks,
Javier
