### ISSUE TITLE
lnvm_rw npages too large(65536). Max:64 supported

### ISSUE THREAD

**Issue by cyb3727** [OpenChannelSSD/qemu-nvme#24]
I create a 128GB pblkdev using the below configuration: 
serial=deadbeef,lver=1,ll2pmode=0,namespaces=16,lnum_lun=8,lnum_pln=4,lpgs_per_plk=256,lsecs_per_pg=4,lsec_size=4086, so each plane has 64 blocks. Because of the OOB, I see that there are 63 blocks. After I use the command:
sudo nvme lnvm create -d nvme0n1 -n mydevice01 -t pblk -b 0 -e 7
sudo mkfs -t ext4 /dev/mydevice01
sudo nvme lnvm create -d nvme0n2 -n mydevice02 -t pblk -b 0 -e 7
sudo mkfs -t ext4 /dev/mydevice02
then the qemu-nvme has the problem:
lnvm_rw npages too large(65536). Max:64 supported

**Comment by javigon** [comment]
Hi,

The configuration looks fine.

The error you are seeing typically occurs when the r/w command is malformed and rqd->nr_ppas is gone out of bounds. Which versions of qemu-nvme and kernel are you using? Have you made any changes?

Thanks,
Javier

**Comment by cyb3727** [comment]
QEMU-NVME kernel is 2.1.50, and  the Ubuntu Linux kernel installed in QEMU-NVME is 4.12.0-rc5. I do not make any changes about QEMU-NVME. I found when I created the first pblkdev using:
sudo nvme lnvm create -d nvme0n1 -n mydevice01 -t pblk -b 0 -e 7
sudo mkfs -t ext4 /dev/mydevice01
which is ok. But when I created the second devices using:
sudo nvme lnvm create -d nvme0n2 -n mydevice02 -t pblk -b 0 -e 7
sudo mkfs -t ext4 /dev/mydevice02
It has the problem.
Thanks.

**Comment by cyb3727** [comment]
I think maybe you need the version comment number:
QEMU-NVME comment number is 6e5dab678c305f22a5f845156b570967910b3484
and linux kernel comment number is 32c1431eea4881a6b17bd7c639315010aeefa452

**Comment by javigon** [comment]
I must admit that I have not tried to instantiate 2 devices in qemu. I would need to look into it closer. Is it important for you to have >1 devices? In any case, can you try to run the workload you intended on a single device?

Regarding the kernel, you can use a newer version. The current one is for-4.15/pblk. As we move with the kernel windows, you will find newer versions in 4.16, 4.17, etc. The repository is located at [1]

[1] https://github.com/OpenChannelSSD/linux

**Comment by cyb3727** [comment]
Thanks for your advice. Yes, I need the create more than two devices.

**Comment by cyb3727** [comment]
Would you tell me how to debug the QEMU-NVME kernel source code?

**Comment by javigon** [comment]
Ok. Please, update pblk and then do the test with a single device to verify that things are ok.

If the problem remains, I'd start by monitoring I/Os on the qemu side to see that they (i) are directed to the right device and (ii) are well formed (ppa list and nr_ppas).

**Comment by cyb3727** [comment]
I have tested a single device to create 16 mydevices, and they work well.
