### ISSUE TITLE
chunk meta is never updated

### ISSUE THREAD

**Issue by youngtack** [OpenChannelSSD/qemu-nvme#34]
Hi @MatiasBjorling,

I'm using kernel-ml-4.17.1-1.el7.elrepo.x86_64 on QEMU NVMe (6f2e658 on master).
Issues I observed:

1. chunk meta is never updated and nvme_exit() is never called.
2. vector chunk reset's mptr is not updated with chunk descriptors.
3. completion queue entry for vector commands doesn't have DW0/1 updated with LBA status.

Didn't you see these on your environment?
I think chunk meta update could be changed as like meta data update.
And it's not easy to estimate workaround for other two.

Thanks,
YT

**Comment by javigon** [comment]
nvme_exit() is only called then the device is removed - this was originally intended for device hotplug.

To test this, you need to name the device (e.g., id="lnvm") and then use the qemu monitor to remove the device (device_del lnvm). Then nvme_exit() will be called and metadata persisted. 

Please pull before doing this, as 1c6303b944ee fixes a bad object reference when triggering this path,

Javier

**Comment by MatiasBjorling** [comment]
Hi YT,

Those haven't been implemented in qemu yet. Do you want to submit fixes or should I look into it?

Thanks!

**Comment by youngtack** [comment]
Hi Javier,

Thanks to let me know qumu monitor. I will give it a try.

Hi Matias,

I'm afraid I can't work on fixes for a while. It will be great if your team can work on it.

Thanks,
YT

**Comment by youngtack** [comment]
closing this issue as another issue #35 is reported.
