### ISSUE TITLE
n->namespaces[i].ctrl != n

### ISSUE THREAD

**Issue by youngtack** [OpenChannelSSD/qemu-nvme#35]
https://github.com/OpenChannelSSD/qemu-nvme/blob/6f2e658b5094a5dbcef34e3f66aa789fdff0b508/hw/block/nvme.c#L2912

As I tried device_del, ns structure is corrupted already at `lnvm_exit()` and `lnvm_chunk_meta_save()` is failing due to the wrong ctrl and chunk meta.

**Comment by javigon** [comment]
I can see there were some cases not implemented. Can you try fixes180618 (branch)?

**Comment by youngtack** [comment]
Thank you, Javier. `fixes180618` works fine.
It's great to init zero sized chunk meta file.
