### ISSUE TITLE
nvme device not found

### ISSUE THREAD

**Issue by Umar895** [OpenChannelSSD/qemu-nvme#39]
Hi everyone,
I am trying to run the qemu-nvme, but facing configuration problems. Following are my configuration settings:
sudo x86_64-softmmu/qemu-system-x86_64 -hda /home/umar/qemu-nvme/ocssd_backend.img --enable-kvm -initrd /boot/initrd.img-4.16.0+ -m 16G -smp 12 -append "root=/dev/sda1"-kernel "/home/umar/linux/arch/x86_64/boot/bzImage" -drive file=/home/umar/blknvme,if=none,id=mynvme -device nvme,drive=mynvme,serial=deadbeef,namespaces=1,lmetasize=16,mdts=10,ldebug=0,lstrict=1,nlbaf=5,lba_index=3 -curses

Which results in BusyBox error i.e "ALERT!  /dev/sda1 does not exist.  Dropping to a shell!"

![selection_006](https://user-images.githubusercontent.com/7709955/43599344-92da40a4-9687-11e8-9701-74d6d61c6be1.png)

Similarly, i tried another recommended configuration by javigon from previous posts, which is as follows:
sudo ../qemu-nvme/x86_64-softmmu/qemu-system-x86_64 -m 16G -smp 12 -s -drive file=/home/home/umar/qemu-nvme/ocssd_backend.img,id=diskdrive,format=raw,if=none -device virtio-blk-pci,drive=diskdrive,scsi=off,config-wce=off,x-data-plane=on -drive file=/home/umar/blknvme,id=extradrive,format=raw,if=none -device nvme,drive=mynvme,serial=deadbeef,namespaces=1,lver=1,lmetasize=16,ll2pmode=0,nlbaf=5,lba_index=3,mdts=10,lnum_lun=4,lnum_pln=2,lsec_size=4096,lsecs_per_pg=4
-device ide-hd,drive=extradrive

Which pops-up with can error "can't find value 'mynvme' ".

I have also tried other configurations, but none of them works fine. Please suggest me, what is missing in the configuration.

Thank you

**Comment by MatiasBjorling** [comment]
Hi Umar,

Try with:

sudo  ../qemu-nvme/x86_64-softmmu/qemu-system-x86_64 -m 4G -smp 4 -s \
-drive file=disk.img,id=diskdrive,format=raw,if=none \
-device virtio-blk-pci,drive=diskdrive,scsi=off,config-wce=off,x-data-plane=on \
-drive file=blknvmedevice,id=mynvme,format=raw,if=none \
-device nvme,drive=mynvme,serial=deadbeef,lnum_pu=4,lstrict=1,meta=0,mc=0,lsecs_per_chk=4096,lws_min=4,lws_opt=8 \
-append "console=ttyS0,kgdboc=ttyS1,115200 root=/dev/vda1" \
-kernel "/home/silverwolf/git/linux/arch/x86_64/boot/bzImage" \
-cpu host --enable-kvm 

Also make sure you're using the latest master. That one implements support for 2.0

**Comment by Umar895** [comment]
Thanks Matias for sharing the configuration. I am currently using the latest master. By using the above configuration settings, the console stuck at booting the kernel as in attached screen-shot.

![selection_001](https://user-images.githubusercontent.com/7709955/43617158-ac80aadc-96c0-11e8-90de-fd2f01c1ccf6.png)
