### ISSUE TITLE
qemu-nvme working with libvirt

### ISSUE THREAD

**Issue by dror-lb** [OpenChannelSSD/qemu-nvme#40]
Hi All
In my LAB i'm currently using libvirt to emulate VMs, i would like to move using qemu-nvme as I'm required to emulate NVME disks on my VMs.
libvirt is able to get XML file with all the required params and transform it to qemu command to create the VM.
1. does libvirt support also working with qemu-nvme? and how? maybe specific libvirt vertion? 
2. does there is any equivalent tool which can preserve this capability?

thanks in advance
Dror

**Comment by MatiasBjorling** [comment]
Hi dror,

Do you want to simulate OCSSD's as well? or is that out of scope?

For libvirt, you'll just have to point it to the qemu-nvme binary. I am however sure that libvirt might not work due to this qemu version being quite old. But it is worth a try.

-Matias
