### ISSUE TITLE
QEMU will not boot

### ISSUE THREAD

**Issue by sooyun802** [OpenChannelSSD/qemu-nvme#44]
Hello,
I am currently using the following options to boot my VM.

```
sudo $HOME/qemu-nvme/bin/qemu-system-x86_64 -m 4G -smp 4 -s \
-vnc :4 \
-drive file={path to vm image},id=diskdrive,format=raw,if=none \
-device virtio-blk-pci,drive=diskdrive,scsi=off,config-wce=off,x-data-plane=on \
-drive file={path to ocssd backend file},id=myocssd,format=raw,if=none \
-device nvme,drive=myocssd,serial=deadbeef,lnum_pu=4,lstrict=1,meta=16,mc=3
```

This is what it looks like when I execute the command.

![inked _li](https://user-images.githubusercontent.com/26572842/45286802-b4ffa080-b521-11e8-8785-4b8c1f755374.jpg)

Are there any more options I need to add to get this to work?

Thank you.

**Comment by MatiasBjorling** [comment]
Looks like you're missing your os image or something to boot from. Did you create an OS image to as the "path to vm image"?

**Comment by MatiasBjorling** [comment]
Ok. Instead of 

-drive file={path to vm image},id=diskdrive,format=raw,if=none \
-device virtio-blk-pci,drive=diskdrive,scsi=off,config-wce=off,x-data-plane=on \

You can try:

-hda {path to vm image} \

Then the virtio acceleration is disabled.
