### ISSUE TITLE
How to run qemu with NVMe device emulation?

### ISSUE THREAD

**Issue by somnode** [OpenChannelSSD/qemu-nvme#45]
What options do I have to run to emulate a general NVMe device other than an Open-Channel SSD?

Or does it work as a general NVMe device if I do not create a target with Open-Channel SSD emulation?

**Comment by MatiasBjorling** [comment]
You can use the normal qemu install to expose annvme drive. The repo only supports nvme as ocssd.

You can also use Keith's original branch if you want. It is available here: http://git.infradead.org/users/kbusch/qemu-nvme.git
