### ISSUE TITLE
making qemu-nvme fails with perl regex error

### ISSUE THREAD

**Issue by XRaccoon** [OpenChannelSSD/qemu-nvme#47]
When making qemu-nvme, the following error happens.

`Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^\@strong{ <-- HERE (.*)}$/ at /home/qemu-nvme/scripts/texi2pod.pl line 320. Makefile:470: recipe for target 'qemu.1' failed make: *** [qemu.1] Error 255`

OS: Ubuntu 18.04.1 LTS
Perl version: V5.26.1

I think the problem is a literal **{** in a regular expression is deprecated and causes a syntax error in perl version 5.26

**Comment by MatiasBjorling** [comment]
Thank you!
