### ISSUE TITLE
nvme drive: Unable to set logical and physical sector size to 512 bytes

### ISSUE THREAD

**Issue by TheSSDGuy** [OpenChannelSSD/qemu-nvme#49]
Hi,

I'm testing the qemu-nvme environment for a research project.
I would like to set the nvme controller to work with 512 bytes log and phy sector size.

This is my command line:
./qemu-system-x86_64
-vga std
-device ide-drive,drive=drv0,serial=0x0
-drive format=raw,file=ubuntu-minimal.img,id=drv0,if=none
-device nvme,drive=drv1,serial=0x1,physical_block_size=512,logical_block_size=512
-drive format=qcow2,file=test.qcow,id=drv1,if=none
-m 2048
-smp 2
--enable-kvm

However, what I get in the guest OS:

sudo fdisk -l /dev/nvme0n1
...
...
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (logical/physical): 4096 bytes / 4096 bytes
...

What am I missing?
Thanks for the help

**Comment by MatiasBjorling** [comment]
Hi,

You can take a look at the nlbaf and lba_index fields. An NVMe drive can have different LBA formats, and you'll select which one you like.

Although, note that the qemu code hardwires the setup from 4K and up. If you want 512 format, you should change the code in hw/block/nvme.c around line 2711.

**Comment by TheSSDGuy** [comment]
Hi Matias,

thanks for helping.
Changing the number of bits in "id_ns->lbaf[j].ds" from 12 to 9 did the trick.

Thanks

**Comment by MatiasBjorling** [comment]
Great!
