### ISSUE TITLE
Qemu window is too small by vnc client

### ISSUE THREAD

**Issue by NikoKVCS** [OpenChannelSSD/qemu-nvme#51]
when i start the qemu nvme vnc server, and use vnc client to display it. I found the resolution is too small. Can i display it fullscreen?

**Comment by MatiasBjorling** [comment]
Take a look at the graphics parameters for qemu. You may want to pass in the std drive to support larger resolutions.

  https://wiki.gentoo.org/wiki/QEMU/Options
