### ISSUE TITLE
Property '.lchannels', '.ltype' not found

### ISSUE THREAD

**Issue by NikoKVCS** [OpenChannelSSD/qemu-nvme#54]
when i types the qemu running command:

sudo $HOME/qemu-nvme/bin/qemu-system-x86_64 -m 4G -enable-kvm ~/qemu-nvme2.0/ubuntu.raw \
> -drive file=ocssd_backend.img,if=none,id=myocssd \
> -device nvme,drive=myocssd,serial=deadbeef,lver=1,ltype=0,lba_index=3,nlbaf=5,lchannels=1,namespaces=1

it shows error   Property '.ltype' not found and Property '.lchannels' not found

**Comment by birkelund** [comment]
Hi @NikoKVCS,

Looks like you are using parameters from an older version of qemu-nvme. [README.md](https://github.com/OpenChannelSSD/qemu-nvme/blob/master/README.md) contains correct instructions for current master.

**Comment by NikoKVCS** [comment]
thank you birkelund!
