### ISSUE TITLE
How to count the P/E cycles of an virtual OCSSD?

### ISSUE THREAD

**Issue by ChaosD** [OpenChannelSSD/qemu-nvme#68]
Hello, I'm surprised the so few issues. LigntNVM is a great tool.
Recently, I'd like to build an open-channel SSD environment to simulate my FTL. And I want to know if Virtual OCSSD can support P/E tracking or evaluating performance？

**Comment by MatiasBjorling** [comment]
Hi,

The qemu here isn't build to evaluate performance. However, you can check out Huaicheng's FEMU - which simulations OCSSDs and also allows performance evaluations. 

It is available here: https://ucare-uchicago.github.io/femu/ 
There is also a paper available that describes it: https://www.usenix.org/system/files/conference/fast18/fast18-li.pdf

**Comment by ChaosD** [comment]
Thanks for your help！I will take your suggestion seriously.
