### ISSUE TITLE
Error when trying to boot kernel 4.12 in qemu-nvme

### ISSUE THREAD

**Issue by nusbaoning** [OpenChannelSSD/qemu-nvme#8]
Installed qemu-nvme and Ubuntu 16.04 in a .img file for the virtual machine.  I have checked that using qemu command "qemu-system-x86_64 -hda openChanSSDtest1.img --enable-kvm -m 4G" can boot the machine normally.

However, when I tried the command from http://openchannelssd.readthedocs.io/en/latest/gettingstarted, "qemu-system-x86_64 -m 4G -smp 1 --enable-kvm -hda openChanSSDtest1.img -append "root=/dev/sda" -initrd /boot/initrd.img-4.12.0-rc6 -kernel "/home/baoning/Downloads/linux-4.12-rc6/arch/x86_64/boot/bzImage" -drive file=blknvme,if=none,id=mynvme -device nvme,drive=mynvme,serial=deadbeef,namespaces=1,lver=1,nlbaf=5,lba_index=3,mdts=10 ",
it showed the following image.
![image](https://user-images.githubusercontent.com/14070574/27630659-b5157ae8-5c28-11e7-8779-ff4d8c2498d0.png)
However, when I input "ls /dev/sda", there exists the device.

I have searched a lot of relevant questions and qemu documents to debug but got no clue.
Do you think it is a command error, or any inconsistency of the kernel version and the qemu-nvm, or anything else? I use kernel 4.12 because I want to use pblk.

**Comment by javigon** [comment]
Can you share your qemu script? Seems that you are missing all the LightNVM specific options for boot: (e.g., lnum_lun=4,lnum_pln=2,lsec_size=4096,lsecs_per_pg=4,lpgs_per_blk=512,ldebug=0,lstrict=1)

**Comment by nusbaoning** [comment]
Thank you so much for replying.
This is my script. 
qemu-system-x86_64 -m 4G -smp 1 --enable-kvm -hda openChanSSDtest1.img -append "root=/dev/sda" -initrd /boot/initrd.img-4.12.0-rc6 -kernel "/home/baoning/Downloads/linux-4.12-rc6/arch/x86_64/boot/bzImage" -drive file=blknvme,if=none,id=mynvme -device nvme,drive=mynvme,serial=deadbeef,namespaces=1,lver=1,nlbaf=5,lba_index=3,mdts=10 

I also added all the options you mentioned and the result was just the same.

**Comment by arpith20** [comment]
I had a similar problem, the order in which you enter the parameters matter. Please try 
-kernel "/home/baoning/Downloads/linux-4.12-rc6/arch/x86_64/boot/bzImage" -append "root=/dev/sda" -initrd /boot/initrd.img-4.12.0-rc6

**Comment by nusbaoning** [comment]
Tried to change the order as you said. Still the same result.

**Comment by arpith20** [comment]
Try it without -initrd /boot/initrd.img-4.12.0-rc6

**Comment by javigon** [comment]
Yes! Thanks @arpith20 👍

**Comment by nusbaoning** [comment]
Then it's kernel panic - not syncing :  VFS : Unable to mount root fs on unkown-block(8,0). 
Actually, I added -initrd to fix this error.

**Comment by javigon** [comment]
Try my current config (below). Then we can see why you get this error.

sudo ../qemu-nvme/x86_64-softmmu/qemu-system-x86_64 -m 16G -smp 12 -s \
-drive file=/home/javigon/development/virtual/vdisk_rocksdb.img,id=diskdrive,format=raw,if=none \
-device virtio-blk-pci,drive=diskdrive,scsi=off,config-wce=off,x-data-plane=on \
-drive file=/home/javigon/development/virtual/extradisk.raw,id=extradrive,format=raw,if=none \
-device nvme,drive=mynvme,serial=deadbeef,namespaces=1,lver=1,lmetasize=16,ll2pmode=0,nlbaf=5,lba_index=3,mdts=10,lnum_lun=4,lnum_pln=2,lsec_size=4096,lsecs_per_pg=4,lpgs_per_b$
-device ide-hd,drive=extradrive \
-drive file=/mnt/eval/block_rocks,if=none,id=mynvme \

**Comment by arpith20** [comment]
Oh, I think this should be it..
it's not -append "root=/dev/sda" but -append "root=/dev/sda1"

**Comment by nusbaoning** [comment]
Yes. That's right! When I use /dev/sda1, everything goes well. Thank you so much!
