### ISSUE TITLE
Unexpected slow speed of simulated nvme device

### ISSUE THREAD

**Issue by nusbaoning** [OpenChannelSSD/qemu-nvme#9]
When I tried to use "dd" command or "cp" command to copy a file to a block device exposed by pblk on nvme device, the speed is extremely slow.
![image](https://user-images.githubusercontent.com/14070574/27782654-f0b09688-6005-11e7-8f3f-37e6df482de2.png)
![image](https://user-images.githubusercontent.com/14070574/27782704-2cdb8000-6006-11e7-8c5d-cf7d236df51a.png)

I'am not sure this is caused by my wrong configuration of nvme device, wrong command running on the device or some kind of shortcomings of the simulated device.

Here is my configuration of nvme device.
nvme -device nvme,drive=mynvme,serial=deadbeef,namespaces=1,lver=1,lmetasize=16,ll2pmode=0,nlbaf=5,lba_index=3,mdts=10,lnum_lun=4,lnum_pln=2,lsec_size=4096,lsecs_per_pg=4,lpgs_per_blk=512,lbbtable=bbtable.qemu,lmetadata=meta.qemu,ldebug=1

Here is how I expose the device.
sudo nvme lnvm init -d nvme0n1
sudo nvme lnvm create -d nvme0n1 --lun-begin=0 --lun-end=3 -n mydevice -t pblk
![image](https://user-images.githubusercontent.com/14070574/27782841-b5f6ccfa-6006-11e7-80a4-41837ff2437a.png)

Here are my dd and cp commands:
dd if=/dev/zero | pv | sudo dd of=/dev/mydevice bs=1M count=144

dd if=/dev/zero of=test.file bs=1M count=100
cp test.file /dev/mydevice
pv test.file > sudo /dev/mydevice

Thank you so much for looking at my question.
Look forward to your reply.

**Comment by javigon** [comment]
Hi,

What's the raw speed with fio?

Try not setting lbbtable, lmetadata, and ldebug=0. Also, make sure that you have no debugging enabled neither on the kernel nor on the qemu side.

Typically, qemu is not about performance, but correctness. However, 15KB/s seems extream.

**Comment by MatiasBjorling** [comment]
Make sure you've boot qemu with kvm. (use --enable-kvm on the qemu command line). Else qemu will use software CPU emulation.

**Comment by nusbaoning** [comment]
I've booted qemu with kvm. 
Removed the parameters you mentioned and no configuration of debug on both sides.
The fio command I used is:
sudo fio -filename=/dev/mydevice -direct=1 -rw=read -bs=1m -size=100G -numjobs=4 -runtime=100 -group_reporting -name=test_read

The result is:
![image](https://user-images.githubusercontent.com/14070574/27784462-b23b6eee-600c-11e7-9274-4f92d6b223a4.png)
Seemed that the io did not access the device.

**Comment by MatiasBjorling** [comment]
Hi, You'll need to write first. Else pblk will just pass the command back

**Comment by nusbaoning** [comment]
Hi, when I tried to use fio and set rw=write, even if I set the runtime=10, it will run endlessly with printing
![image](https://user-images.githubusercontent.com/14070574/27785484-5a25e2da-6010-11e7-9776-da399fbeb6fe.png)

**Comment by hailfinger** [comment]
That's an issue I was seeing as well.  Check https://github.com/OpenChannelSSD/linux/issues/28 for my attempts to debug it. I haven't yet figured out if this is a qemu bug, a guest kernel bug, or a bug of some software on the host.

Which Ubuntu version do you use on the host? Which kernel version do you use on the guest?

I had such failures with Ubuntu 14.04 on the host with latest qemu-nvme git and mainline kernel 4.12 on the guest. With Ubuntu 16.04 on the host with qemu commit 6e5dab678c30 reverted, kernel 4.13-git on the guest it works.

**Comment by nusbaoning** [comment]
My host is Ubuntu 16.04 with kernel 4.4.0 with qemu-nvme git.
My guest is mainline kernel 4.12-rc6 on Ubuntu 16.04.

**Comment by javigon** [comment]
@nusbaoning Look at the issue that hailfinger referred to. He experienced something similar. 

Please pull the latest changes for qemu.

**Comment by nusbaoning** [comment]
Hi. I have already tried the latest version of qemu with commit 6e5dab678c305f22a5f845156b570967910b3484 with kernel 4.12.2 but still failed.
What is the kernel version you are using? Any update for pblk module needed?
Thank you.

**Comment by nusbaoning** [comment]
One thing I think may be useful is that when I used the latest version of qemu, the dd command works well. However, fio still fails and can't install ext4 file system on the device.
